import Head from 'next/head'
import Header from '../Components/Header'
import Nav from '../Components/Nav'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* {Header} */}
      <Header />

      {/* {Nav} */}
        <Nav />
      {/* { Body } */}
  
    </div>
  )
}
